---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk-alpine'

inputs:
  - name: pcfdemo
  - name: candidate-release
  - name: version

outputs:
  - name: prepare-final-output

run:
  path: pcfdemo/ci/tasks/prepare-final.sh
