---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk-alpine'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: pcfdemo

run:
  path: pcfdemo/ci/tasks/unit.sh
